### ISSUE TITLE
httpkey does not fetch the URL

### ISSUE THREAD

**Issue by thehackerish** [leoloobeek/keyring#2]
I know this is an old project, but I'd appreciate if you could provide some guidance.
Using the `httpkey` with the URL and a dummy user-agent in JScript embeds them in the JS file, but I see no http request made to my server during the decryption. I had ti manually input the hash of the response from the server in the combos inside the JS file in order to work, but that defeats the purpose of controlling the key.

Here is the yaml config file:

```
language: jscript
payloadFile: empire-plain.js
outputFile: empire-enc-web.js
keyers:
  -
    name: httpkey
    inputs:
      - https://my.site/key/get
      - Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko
    keydata: 26bbfb8460185c683077a2b37c84ceaff649028af69222a4b30d130951ef539aebbf16101969ef2a337fe0edd0b31894be6ac443d0a35e635b00d7c70674cae3
retries: 0
sleep: 0
```

The keydata was obtained by running `keyring --request https://my.site/key/get`

I run the command `keyring  --config examples/js-test-config-web.yml`

When running the JS file in debug mode, I see it is trying to decrypt using each item in the combo list, but no request is made to my server, and obviously the program exists.
